apiVersion: v1
kind: Namespace
metadata:
  name: email-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
  namespace: email-service
  labels:
    app: email-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
        - name: email-service
          image: mash02/email-service:latest
          ports:
            - containerPort: 50058
          env:
          - name: EMAIL_SERVICE_URL
            value: 0.0.0.0:50058
          - name: SMTP_HOST
            value: smtp.gmail.com
          - name: SMTP_PASS
            value: 
          - name: SMTP_PORT
            value: "465"
          - name: SMTP_USER
            value: projects.raizurai@gmail.com
          # envFrom:
          #   - secretRef:
          #       name: email-service-secret
---
apiVersion: v1
kind: Service
metadata:
  name: email-service
  namespace: email-service
spec:
  selector:
    app: email-service
  ports:
    - protocol: TCP
      port: 50058
      targetPort: 50058
  type: ClusterIP
